version: '2'
services:
    mysql:
            image: mysql:latest
            ports:
                - '3308:3306'
            container_name: mysql
            restart: always
            environment:
              - MYSQL_ROOT_PASSWORD=123456
              - MYSQL_DATABASE=quiz
            networks:
              - code-network
    quiz-flask:
            image: johnkiller/quiz-backend:latest
            depends_on:
                - mysql
            ports:
                - '801:8888'
            volumes:
                - /root/quiz2:/usr/src/app